### ISSUE TITLE
No option to set up new Nano account

### ISSUE THREAD

**Issue by RawDawg** [aaronk6/Nano-MoneyMoney#3]
Added the .lua to the extensions folder but there is no Nano account type when I want to add a new account. Other extension accounts (Binance, Coinbase, Coinbase Pro) show up as expected. 

MoneyMoney 2.3.35 Retail, MacOS 10.13.6

**Comment by RawDawg** [comment]
No idea why but deleting and adding the extension again a few times made it work suddenly.

**Comment by aaronk6** [comment]
That’s weird. Thanks for following up and let me know if you encounter this again.
