### ISSUE TITLE
Accounts not updating

### ISSUE THREAD

**Issue by marothe** [aaronk6/Nano-MoneyMoney#4]
Accounts do not seem to update for over 2 months now. 

Following error message:

> Das SSL-Zertifikat des API-Servers Ihrer Bank wurde von macOS 13.0.1 als ungültig abgewiesen. Bitte versuchen Sie es später noch einmal oder wenden Sie sich für weitere Informationen an den Support Ihrer Bank.

Any ideas?

**Comment by marothe** [comment]
I believe "nanocrawler" is not working anymore, as it redirects to "nanolooker". Any plans to fix this? Or this is project dead? @aaronk6 

Thanks!

**Comment by aaronk6** [comment]
Hi @marothe! Not necessarily dead, but I stopped using the extension for myself. Anyway happy to take a look next week to see if it’s an easy fix!

**Comment by marothe** [comment]
Hi @aaronk6 - thank you so much! Would be awesome, I still use it :-). It seems that nanolooker also has a API, not sure though.

Another question: Are you using another extension or do you just not hold nano anymore (this might be a too personal question, just wanting to know if you are using another extension to track your crypto in MM).

Thanks! Happy new year :-).

**Comment by marothe** [comment]
Fixed it: https://github.com/aaronk6/Nano-MoneyMoney/pull/5

**Comment by aaronk6** [comment]
Awesome! I’ll give it a try later today and send it to MoneyMoney to get it signed.
